### ISSUE TITLE
Update Homebrew Cask URL

### ISSUE THREAD

**Issue by reitermarkus** [kbystk/amp#2]
Hi, we just wanted to let you know that you are still linking to the old Homebrew Cask homepage (`caskroom.io`) in [`5c3c04e1be23a10017086e75.html`](https://github.com/kbystk/amp/blob/2d60cb397a4379b25e78ecad40e1dd777acfcd47/public/5c3c04e1be23a10017086e75.html). This domain expired a few years ago and is not controlled by Homebrew anymore.

When you get a chance, please update the link to https://brew.sh/ or https://formulae.brew.sh/cask/.

Thank you,
the Homebrew team.

**Comment by e-jigsaw** [comment]
Thanks, I will note postscript section.
